---
name: M02 - 元件參數敏感度分析 任務追蹤
about: 元件參數敏感度分析 模組任務描述
title: "[M02] 元件參數敏感度分析"
labels: module:M02, task
assignees: ''

---

## 📌 任務說明

請填寫模組 M02 的任務目的與預期功能。

## 📂 相關檔案

- `modules/M02_m02.py`
- `metadata/M02_m02.yaml`
- `logs/M02.log`
- `figure/M02_result.png`

## ✅ 驗收條件

- 模組可被主程式調用
- 測試輸出與預期相符
- 記錄必要日誌與錯誤處理
