---
name: M03 - 差分演化演算法最佳化 任務追蹤
about: 差分演化演算法最佳化 模組任務描述
title: "[M03] 差分演化演算法最佳化"
labels: module:M03, task
assignees: ''

---

## 📌 任務說明

請填寫模組 M03 的任務目的與預期功能。

## 📂 相關檔案

- `modules/M03_m03.py`
- `metadata/M03_m03.yaml`
- `logs/M03.log`
- `figure/M03_result.png`

## ✅ 驗收條件

- 模組可被主程式調用
- 測試輸出與預期相符
- 記錄必要日誌與錯誤處理
