---
name: M05 - Ngspice CLI 模擬器介接 任務追蹤
about: Ngspice CLI 模擬器介接 模組任務描述
title: "[M05] Ngspice CLI 模擬器介接"
labels: module:M05, task
assignees: ''

---

## 📌 任務說明

請填寫模組 M05 的任務目的與預期功能。

## 📂 相關檔案

- `modules/M05_m05.py`
- `metadata/M05_m05.yaml`
- `logs/M05.log`
- `figure/M05_result.png`

## ✅ 驗收條件

- 模組可被主程式調用
- 測試輸出與預期相符
- 記錄必要日誌與錯誤處理
