---
name: M06 - 嵌入參數並生成 SPICE 模型 任務追蹤
about: 嵌入參數並生成 SPICE 模型 模組任務描述
title: "[M06] 嵌入參數並生成 SPICE 模型"
labels: module:M06, task
assignees: ''

---

## 📌 任務說明

請填寫模組 M06 的任務目的與預期功能。

## 📂 相關檔案

- `modules/M06_m06.py`
- `metadata/M06_m06.yaml`
- `logs/M06.log`
- `figure/M06_result.png`

## ✅ 驗收條件

- 模組可被主程式調用
- 測試輸出與預期相符
- 記錄必要日誌與錯誤處理
