name: ✅ 檢查 YAML 格式正確性

on:
  push:
    paths:
      - 'metadata/**/*.yaml'
      - '.github/workflows/check_yaml.yml'
  pull_request:
    paths:
      - 'metadata/**/*.yaml'
      - '.github/workflows/check_yaml.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: 取得專案程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝 YAML 模組
        run: pip install pyyaml

      - name: 執行 YAML 格式檢查
        run: python check_yaml_format.py
